spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000

jwt:
  secret: ${JWT_SECRET:bookstore-super-secret-key-for-jwt-authentication-2024}
